version: '3'

volumes:
  database: {}
  staticfiles: {}

services:
  postgres:
    image: "postgres"
    volumes:
      - database:/var/lib/postgresql/data:Z
    ports:
      - 5432:5432
    env_file:
      - ./.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
